env:
  IMAGE_NAME: pycampers/micropython
  TEMP_IMAGE: $IMAGE_NAME:$CIRRUS_TASK_ID
  RELEASE_IMAGE: $IMAGE_NAME:${CIRRUS_TAG:-$CIRRUS_BRANCH}

docker_builder:
  name: Build docker image
  build_script: |
    docker pull $RELEASE_IMAGE
    docker build --cache-from=$RELEASE_IMAGE -t $TEMP_IMAGE .

    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
    docker tag $TEMP_IMAGE $RELEASE_IMAGE
    docker push $RELEASE_IMAGE

build_ports_task:
  name: Build ports
  container:
    image: $TEMP_IMAGE
  depends_on: Build docker image
  env:
    matrix:
      - MPY_PORT: stm32
      - MPY_PORT: qemu-arm
      - MPY_PORT: unix-coverage
      - MPY_PORT: unix-standard
      - MPY_PORT: unix-nanobox
      - MPY_PORT: unix-stackless
      - MPY_PORT: windows
      - MPY_PORT: esp32
      - MPY_PORT: esp8266
      - MPY_PORT: nrf
      - MPY_PORT: bare-arm
      - MPY_PORT: cc3200
      - MPY_PORT: samd
      - MPY_PORT: teensy
  build_script: docker run -v $PWD:$PWD -w $PWD $RELEASE_IMAGE ci-scripts/$MPY_PORT.sh
