image: docker:stable-git

variables:
  DOCKER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MAKEOPTS: "-j4"
  CACHE_DIR: $HOME/persist

before_script:
  - docker info
  - RELEASE_IMAGE=$(ci-scripts/get-release-img.sh)
  - echo $RELEASE_IMAGE

build:
  stage: build
  script:
    - env
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $DOCKER_TEST_IMAGE
    - docker build --cache-from=$DOCKER_TEST_IMAGE -t $DOCKER_TEST_IMAGE .

stm32:
  &build-port
  stage: test
  image: $DOCKER_TEST_IMAGE
  script:
    - ci-scripts/$CI_JOB_NAME.sh
qemu-arm: *build-port
unix-coverage: *build-port
unix-standard: *build-port
unix-nanobox: *build-port
unix-stackless: *build-port
windows: *build-port
esp32: *build-port
esp8266: *build-port
nrf: *build-port
bare-arm: *build-port
cc3200: *build-port
samd: *build-port
teensy: *build-port
