language: c

cache:
  directories:
    - "${HOME}/mpy-cross"

env:
  global:
    - MAKEOPTS="-j4"

# define the CI matrix
jobs:
  include:
    # build mpy-cross
    - stage: mpy-cross
      install:
        - gcc --version
        - python3 --version
      script:
        - make ${MAKEOPTS} -C mpy-cross clean
        - make ${MAKEOPTS} -C mpy-cross

    # unix port
    - stage: test
      script:
        - ls mpy-cross
        - make ${MAKEOPTS} -C ports/unix deplibs
        - make ${MAKEOPTS} -C ports/unix

    # stm32 port
    - stage: test
      install:
        - sudo apt-get install -y --force-yes gcc-arm-none-eabi
        - arm-none-eabi-gcc --version
      script:
        - ls mpy-cross
        - make ${MAKEOPTS} -C ports/stm32

# define the successive stages
stages:
  - name: mpy-cross
  - name: test
