dist: xenial
language: minimal
services:
  - docker
cache:
  directories:
    - "${HOME}/persist"
env:
  global:
    - MAKEOPTS="-j4"
    - IMAGE_NAME=pycampers/micropython
    - TAG=$(travis/get-tag.sh)
    - IMAGE=$IMAGE_NAME:$TAG
    - IMG_TAR=$HOME/persist/docker-image-$TAG.tar
git:
  submodules: false

stages:
  - name: build
  - name: test

jobs:
  include:
    - stage: build
      script:
        - docker load -i $IMG_TAR

        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        - docker pull $IMAGE
        - docker build --cache-from $IMAGE -t $IMAGE .
        - docker push $IMAGE

        - docker save -o $IMG_TAR $IMAGE

    - stage: test
      env:
        - PORT=stm32
        - PORT=qemu-arm
        - PORT=unix-coverage
        - PORT=unix-standard
        - PORT=unix-nanobox
        - PORT=unix-stackless
        - PORT=windows
        - PORT=esp32
        - PORT=esp8266
        - PORT=nrf
        - PORT=bare-arm
        - PORT=cc3200
        - PORT=samd
        - PORT=teensy
      script:
        - docker load -i $IMG_TAR
        - IMG_TAG=$(travis/get-img-tag.sh)
        - docker run -v $PWD:$PWD -w $PWD $IMG_TAG travis/${PORT}.sh
