dist: xenial
language: minimal

services:
  - docker
git:
  submodules: false
env:
  global:
    - MAKEOPTS="-j4"
    - CACHE_DIR=${HOME}/persist
    - IMAGE_NAME=pycampers/micropython
    - IMAGE_TAG=$(travis/get-tag.sh)
    - IMAGE=${IMAGE_NAME}:${IMAGE_TAG}
    - IMAGE_TAR=${HOME}/persist/docker-image-${TRAVIS_COMMIT}.tar
cache:
  directories:
    - $CACHE_DIR

stages:
#  - name: build
  - name: test

jobs:
  include:
#    - stage: build
#      script:
#        - mkdir -p ${CACHE_DIR}
#
#        - echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
#        - docker load -i ${IMAGE_TAR} || true
#        - docker pull ${IMAGE}
#
#        - docker build --cache-from ${IMAGE} -t ${IMAGE} .
#
#        - docker push ${IMAGE}
#        - docker save -o ${IMAGE_TAR} ${IMAGE}

    - stage: test
      matrix:
        include:
          - env: PORT=stm32
          - env: PORT=qemu-arm
          - env: PORT=unix-coverage
          - env: PORT=unix-standard
          - env: PORT=unix-nanobox
          - env: PORT=unix-stackless
          - env: PORT=windows
          - env: PORT=esp32
          - env: PORT=esp8266
          - env: PORT=nrf
          - env: PORT=bare-arm
          - env: PORT=cc3200
          - env: PORT=samd
          - env: PORT=teensy
      script:
#        - docker load -i ${IMAGE_TAR} || true
        - docker run -v ${PWD}:${PWD} -w ${PWD} ${IMAGE} travis/${PORT}.sh
