version: 2
jobs:
  build:
   machine:
      image: ubuntu-1604:201903-01
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - checkout
        - build:
            name: Build docker image
            command: |
              docker build -t micropython .
