version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Setup env vars
          command: |
            TAG=$(git describe --exact-match HEAD 2> /dev/null)
            echo "hello?"

            if [ $? -ne 0 ]; then
            	TAG="master"
            fi

            echo $TAG
            echo "export IMG_TAG=pycampers/micropython:$TAG" >> $BASH_ENV

      - run:
          name: Build docker image
          command: |
            echo "Building image $IMG_TAG"
            docker build -t $IMG_TAG .

      - run:
          name: Push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $IMG_TAG
  test:
    parallelism: 4
    docker:
      - image: $IMG_TAG
    steps:
      - checkout
      - run:
          name: Test stm32 port
          command: |
            git submodule update --init lib/lwip lib/mbedtls lib/stm32lib
            make ${MAKEOPTS} -C mpy-cross
            make ${MAKEOPTS} -C ports/stm32
            make ${MAKEOPTS} -C ports/stm32 BOARD=PYBV11 MICROPY_PY_WIZNET5K=5200 MICROPY_PY_CC3K=1
            make ${MAKEOPTS} -C ports/stm32 BOARD=PYBD_SF2
            make ${MAKEOPTS} -C ports/stm32 BOARD=STM32F769DISC CFLAGS_EXTRA='-DMICROPY_PY_THREAD=1'
            make ${MAKEOPTS} -C ports/stm32 BOARD=STM32L476DISC
            make ${MAKEOPTS} -C ports/stm32/mboot BOARD=PYBD_SF6
