version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            TAG=pycampers/micropython:$(git describe --tags --abbrev=0)
            docker build -t $TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $TAG
