version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            TAG=$(git describe --tags --abbrev=0)
            docker build -t pycampers/micropython:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push CircleCI-Public/circleci-demo-docker:$TAG
