version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      # Run a step to print what branch our code base is on.
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      - run:
          name: "What branch am I on now?"
          command: echo $CIRCLE_BRANCH
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}

      - run:
          name: Setup env vars
          command: |
            TAG=pycampers/micropython:$(git describe --tags --abbrev=0)
            echo $TAG
            echo "$TAG"
            echo "TAG=$TAG"
            echo "export TAG=$TAG"
            echo "export TAG=$TAG" >> $BASH_ENV

      - run:
          name: Print env vars
          command: echo ${TAG}

      - run:
          name: Build docker image
          command: |
            docker build -t $TAG .

      - run:
          name: Push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $TAG
  test:
    parallelism: 4
    docker:
      - image: $TAG
    steps:
      - checkout
      - run:
          name: Test stm32 port
          command: |
            git submodule update --init lib/lwip lib/mbedtls lib/stm32lib
            make ${MAKEOPTS} -C mpy-cross
            make ${MAKEOPTS} -C ports/stm32
            make ${MAKEOPTS} -C ports/stm32 BOARD=PYBV11 MICROPY_PY_WIZNET5K=5200 MICROPY_PY_CC3K=1
            make ${MAKEOPTS} -C ports/stm32 BOARD=PYBD_SF2
            make ${MAKEOPTS} -C ports/stm32 BOARD=STM32F769DISC CFLAGS_EXTRA='-DMICROPY_PY_THREAD=1'
            make ${MAKEOPTS} -C ports/stm32 BOARD=STM32L476DISC
            make ${MAKEOPTS} -C ports/stm32/mboot BOARD=PYBD_SF6
