image: Visual Studio 2017
clone_depth: 1
skip_tags: true

environment:
  # Python version used
  MICROPY_CPYTHON3: c:/python38/python.exe

init:
  # Set build version number to commit to be travis-like
- ps: Update-AppveyorBuild -Version $env:appveyor_repo_commit.substring(0,8)

build_script:
- ps: |
    $upyDir = $env:APPVEYOR_BUILD_FOLDER
    $msys2Bash = "C:/msys64/usr/bin/bash.exe"
    $VerbosePreference = [Management.Automation.ActionPreference]::Continue
    . "$upyDir/ports/windows/build.ps1"

    @(
        @{platform = "Win32"; configuration = "Debug"; variant = "standard"},
        @{platform = "Win32"; configuration = "Release"; variant = "standard"},
        @{platform = "x64"; configuration = "Debug"; variant = "standard"},
        @{platform = "x64"; configuration = "Release"; variant = "standard"},
        @{platform = "x64"; configuration = "Release"; variant = "dev"}
    ) |
        ForEach-Object {
            $buildOpts = "/p:Platform=$($_.platform);Configuration=$($_.configuration);PyVariant=$($_.variant)"
            Invoke-MsvcBuild $uPydir $buildOpts 
            Invoke-MsvcTests $uPydir $buildOpts
        }

    @(
        @{platform = "MINGW32"; variant = "standard"},
        @{platform = "MINGW64"; variant = "standard"}
        @{platform = "MINGW64"; variant = "dev"}
    ) |
        ForEach-Object {
            $makeOpts = "-j4 V=1 PYTHON=$($env:MICROPY_CPYTHON3)"
            # Use distinct BINDIR so we can pick up artifacts without each build overwriting the output of the previous one.
            $mpycrossMakeOpts = "$makeOpts BINDIR=build/$($_.platform)"
            $upyMakeOpts = "$makeOpts VARIANT=$($_.variant) BINDIR=build-$($_.variant)/$($_.platform)"
            Invoke-MingwBuild $uPydir $_.platform $msys2Bash $mpycrossMakeOpts $upyMakeOpts
            Invoke-MingwTests $uPydir $_.platform $msys2Bash $upyMakeOpts
        }

artifacts:
  - path: mpy-cross/build/Releasex64/mpy-cross.exe
    name: mpy-cross-msvc
  - path: mpy-cross/build/MINGW64/mpy-cross.exe
    name: mpy-cross-mingw
  - path: ports/windows/build-standard/Releasex64/micropython.exe
    name: micropython-msvc
  - path: ports/windows/build-standard/MINGW64/micropython.exe
    name: micropython-mingw
