name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup env vars
        run: |
          TAG=$(git describe --exact-match HEAD 2> /dev/null || echo "master")
          export IMG_TAG=pycampers/micropython:$TAG
          echo $IMG_TAG
      - name: Print env vars
        run: |
          echo $IMG_TAG

      - name: Build docker image
        uses: actions/docker/cli@master
        with:
          args: docker build -t $IMG_TAG .